# docker compose file for nodejs app and mongodb-community

version: "3.8"

services:
  todo:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: todo-app
    image: nodejs-todo-app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mongodb://todo:todo888@localhost:27017/todolist?authSource=admin
    networks:
      - server-network
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGODB_INITDB_ROOT_USERNAME: todo
      MONGODB_INITDB_ROOT_PASSWORD: todo888
      MONGODB_DATABASE: todolist
    ports:
      - 27017:27017
networks:
  server-network: