version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo
      MONGO_INITDB_ROOT_PASSWORD: todo888
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: todo-app
    image: nodejs-todo-app
    depends_on:
      - mongo_db
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      DATABASE_URL: mongodb://mongo_db:27017/todolist?authSource=admin
    volumes:
      - .:/usr/src/app

volumes:
  mongo_db: {}