version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: todo-app
    image: nodejs-todo-app
    depends_on:
      - mongo_db
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      DATABASE_URL: mongodb://mongo_db:27017/${MONGO_INITDB_DATABASE}?authSource=admin

volumes:
  mongo_db: {}