# Get all todos
GET http://localhost:3000/api/v1/todos

# Get a single todo
GET http://localhost:3000/api/v1/todos/id

# Create a todo
POST http://localhost:3000/api/v1/todos/
Content-Type: application/json

{
  "title": "Learn Node.js",
  "content": "Learn Node.js and build REST APIs"
}

# Update a todo
PATCH  http://localhost:3000/api/v1/todos/id
Content-Type: application/json

{
  "title": "Learn Node.js",
  "content": "updated Learn Node.js and build REST APIs"
}

# Delete a todo
DELETE http://localhost:3000/api/v1/todos/id